import os
import json
import time
import requests
import lxml.html

JSON_REQUIRED_DETAILS = {'result', 'language', 'problem_id', 'id', 'contest_id'}

LANGUAGE_EXTENSIONS = {
    '><>': 'ook',
    'AWK': 'awk',
    'Ada': 'adb',
    'Assembly x64': 'asm',
    'Bash': 'sh',
    'Brainfuck': 'bf',
    'C': 'c',
    'C#': 'cs',
    'C++': 'cpp',
    'COBOL': 'cbl',
    'Carp': 'carp',
    'Ceylon': 'ceylon',
    'Clojure': 'clj',
    'Common Lisp': 'lisp',
    'Crystal': 'cr',
    'Cyber': 'cy',
    'Cython': 'pyx',
    'D': 'd',
    'Dart': 'dart',
    'Dash': 'dsh',
    'ECLiPSe': 'ecl',
    'Elixir': 'ex',
    'Emacs Lisp': 'el',
    'Erlang': 'erl',
    'F#': 'fs',
    'Factor': 'factor',
    'Forth': 'fth',
    'Fortran': 'f',
    'Go': 'go',
    'Haskell': 'hs',
    'Haxe': 'hx',
    'Java': 'java',
    'JavaScript': 'js',
    'Julia': 'jl',
    'Koka': 'kk',
    'Kotlin': 'kt',
    'LLVM IR': 'll',
    'Lua': 'lua',
    'Mercury': 'm',
    'MoonScript': 'moon',
    'Nibbles': 'nib',
    'Nim': 'nim',
    'OCaml': 'ml',
    'Objective-C': 'm',
    'Octave': 'm',
    'PHP': 'php',
    'Pascal': 'pas',
    'Perl': 'pl',
    'PowerShell': 'ps1',
    'Prolog': 'pl',
    'Python': 'py',
    'R': 'r',
    'Racket': 'rkt',
    'Raku': 'raku',
    'ReasonML': 're',
    'Ruby': 'rb',
    'Rust': 'rs',
    'SageMath': 'sage',
    'Scala': 'scala',
    'Scheme': 'scm',
    'Sed': 'sed',
    'Seed7': 'sd7',
    'Standard ML': 'sml',
    'Swift': 'swift',
    'Text': 'txt',
    'TypeScript': 'ts',
    'Unison': 'u',
    'Unlambda': 'unl',
    'V': 'v',
    'Vim': 'vim',
    'Visual Basic': 'vb',
    'Whitespace': 'ws',
    'Zig': 'zig',
    'Zsh': 'zsh',
    'bc': 'bc',
    'dc': 'dc',
    'jq': 'jq',
    'なでしこ': 'nako',
    'プロデル': 'pds',
}

KENKOOOO_SLEEP_TIME = 1
ATCODER_SLEEP_TIME = 3


def get_submissions_info(username):
    cur = 0

    while True:
        url = f'https://kenkoooo.com/atcoder/atcoder-api/v3/user/submissions?user={username}&from_second={cur}'

        submissions = json.loads(requests.get(url).text)
        if not submissions:
            break

        for submission in submissions:
            for detail in JSON_REQUIRED_DETAILS:  # Submission doesn't have all the required details
                if detail not in submission:
                    print(f'[Atcoder] ERROR: Missing "{detail}" in {submission}')
                    break

            if submission['result'] == 'AC':
                submission_extension = ''
                for language in LANGUAGE_EXTENSIONS:
                    if submission['language'].startswith(language):
                        if len(language) > len(submission_extension):
                            submission_extension = LANGUAGE_EXTENSIONS[language]

                yield {
                    'extension': submission_extension,
                    'language': submission['language'],
                    'problemID': submission['problem_id'],
                    'submissionID': submission['id'],
                    'problemURL': f'https://atcoder.jp/contests/{submission["contest_id"]}/tasks/{submission["problem_id"]}',
                    'scrapeURL': f'https://atcoder.jp/contests/{submission["contest_id"]}/submissions/{submission["id"]}'
                }

            cur = submission['epoch_second'] + 1

        time.sleep(KENKOOOO_SLEEP_TIME)  # One second per API call


def save_submissions(username, directory):
    def save_submission(submission_info):
        result = lxml.html.fromstring(requests.get(submission_info['scrapeURL']).text)
        code = result.xpath('//*[@id="submission-code"]')[0].text

        filename = f'{submission_info["submissionID"]}.{submission_info["extension"]}'

        local_directory = f'{directory}/{submission_info["language"]}/{submission_info["problemID"]}'
        os.makedirs(f'{directory}/{local_directory}', exist_ok=True)

        location = f'{directory}/{local_directory}/{filename}'
        with open(location, 'w+') as file:
            file.write(code)

        info_location = f'{directory}/{local_directory}/__info.txt'
        with open(info_location, 'w+') as file:
            file.write('# This text file was auto-generated by UpCode\n\n')
            file.write(f'Problem link: {submission_info["problemURL"]}')

        print(f'[Atcoder] Updated {location} successfully')
        yield f'{local_directory}/{filename}', f'{local_directory}/__info.txt'

        time.sleep(ATCODER_SLEEP_TIME)

    failed_submissions = []
    for current_submission_info in get_submissions_info(username):
        try:
            yield from save_submission(current_submission_info)

        except Exception as e:
            print(f'[Atcoder] ERROR: {e}  -->  {current_submission_info["submissionID"]}')
            print('[Atcoder] Pausing temporarily to prevent rate limiting')
            failed_submissions.append(current_submission_info)
            time.sleep(ATCODER_SLEEP_TIME * 20)

    if failed_submissions:
        print('[Atcoder] Attempting to save failed submissions')
        for current_submission_info in failed_submissions:
            try:
                yield from save_submission(current_submission_info)

            except Exception as e:
                print(f'[Atcoder] ERROR: {e}  -->  {current_submission_info["submissionID"]}')
                print('[Atcoder] Skipping')

    else:
        print('[Atcoder] No failed submissions')

    print('[Atcoder] Finished')


if __name__ == '__main__':
    save_submissions('crap_the_coder', 'Atcoder')
