import os
import json
import time
import requests
import lxml.html

CODECHEF_SLEEP_TIME = 3


def get_submissions_id(username):
    url = f'https://www.codechef.com/recent/user?page=0&user_handle={username}'
    data = json.loads(requests.get(url).text)
    page_count = int(data['max_page'])

    page = 0
    while True:
        submissions_parsed = lxml.html.fromstring(data['content'])

        verdicts = submissions_parsed.xpath('/html/body/div/div/table/tbody/tr/td[3]/span/@title')
        submission_urls = submissions_parsed.xpath('/html/body/div/div/table/tbody/tr/td[5]/a')

        for verdict, submission_url in zip(verdicts, submission_urls):
            if verdict == 'accepted' and submission_url.attrib['class'] != 'disabled':
                yield submission_url.attrib['href'].split('/')[-1]

        page += 1
        if page >= page_count:
            break

        time.sleep(CODECHEF_SLEEP_TIME)

        url = f'https://www.codechef.com/recent/user?page={page}&user_handle={username}'
        data = json.loads(requests.get(url).text)


def save_submissions(username, directory):
    def save_submission(submission_id):
        code = json.loads(requests.get(f'https://www.codechef.com/api/submission-code/{submission_id}').text)
        details = json.loads(requests.get(f'https://www.codechef.com/api/submission-details/{submission_id}').text)

        contest_code = x if (x := details['data']['other_details']['contestCode']) else 'Practice'
        problem_code = details['data']['other_details']['problemCode']

        filename = f'{submission_id}.{code["data"]["language"]["extension"]}'

        local_directory = f'{code["data"]["language"]["full_name"]}/{contest_code}-{problem_code}'
        os.makedirs(f'{directory}/{local_directory}', exist_ok=True)

        location = f'{directory}/{local_directory}/{filename}'
        with open(location, 'w+') as file:
            file.write(code['data']['code'])

        info_location = f'{directory}/{local_directory}/__info.txt'
        with open(info_location, 'w+') as file:
            file.write('# This text file was auto-generated by UpCode\n\n')
            file.write(f'Problem link: www.codechef.com{details["data"]["other_details"]["problemUrl"]}')

        print(f'[CodeChef] Updated {location} successfully')
        yield f'{local_directory}/{filename}', f'{local_directory}/__info.txt'

        time.sleep(CODECHEF_SLEEP_TIME)

    failed_submissions = []
    for current_submission_id in get_submissions_id(username):
        try:
            yield from save_submission(current_submission_id)

        except Exception as e:
            print(f'[CodeChef] ERROR: {e}  -->  {current_submission_id}')
            print('[CodeChef] Pausing temporarily to prevent rate limiting')
            failed_submissions.append(current_submission_id)
            time.sleep(CODECHEF_SLEEP_TIME * 20)

    if failed_submissions:
        print('[CodeChef] Attempting to save failed submissions\n')
        for current_submission_id in failed_submissions:
            try:
                yield from save_submission(current_submission_id)

            except Exception as e:
                print(f'[CodeChef] ERROR: {e}  -->  {current_submission_id}')
                print('[CodeChef] Skipping')

    else:
        print('[CodeChef] No failed submissi    ons\n')

    print('[CodeChef] Finished')


if __name__ == '__main__':
    save_submissions('crap_the_coder', 'CodeChef')
