import os
import json
import time
import requests
import lxml.html

LANGUAGE_EXTENSIONS = {
    'GCC': 'c',
    'C++': 'cpp',
    'G++': 'cpp',
    'C#': 'cs',
    'D DMD': 'd',
    'Go': 'go',
    'Haskell': 'hs',
    'Java': 'java',
    'Kotlin': 'kt',
    'OCaml': 'ml',
    'Delphi': 'pas',
    'Pascal': 'pas',
    'Perl': 'pl',
    'PHP': 'php',
    'Python': 'py',
    'PyPy': 'py',
    'Ruby': 'rb',
    'Rust': 'rs',
    'Scala': 'scala',
    'JavaScript': 'js',
    'Node.js': 'js',
}

CODEFORCES_SLEEP_TIME = 5


def get_submissions_info(username):
    url = f'https://codeforces.com/api/user.status?handle={username}&from=1&count=1000000000'
    data = json.loads(requests.get(url).text)

    time.sleep(CODEFORCES_SLEEP_TIME)

    if data['status'] != 'OK':
        print(f'[CodeForces] ERROR: {data["comment"]}\n')
        return

    for submission in data['result']:
        submission_extension = ''
        for language in LANGUAGE_EXTENSIONS:
            if language in submission['programmingLanguage']:
                if len(language) > len(submission_extension):
                    submission_extension = LANGUAGE_EXTENSIONS[language]

        if submission['verdict'] == 'OK':
            yield {
                'extension': submission_extension,
                'language': submission['programmingLanguage'],
                'problemID': str(submission['contestId']) + submission['problem']['index'],
                'submissionID': submission['id'],
                'problemURL': f'https://codeforces.com/contest/{submission["problem"]["contestId"]}/problem/{submission["problem"]["index"]}',
                'scrapeURL': f'https://codeforces.com/contest/{submission["contestId"]}/submission/{submission["id"]}'
            }


def save_submissions(username, directory):
    def save_submission(submission_info):
        result = lxml.html.fromstring(requests.get(submission_info['scrapeURL']).text)
        code = result.xpath('//*[@id="program-source-text"]')[0]

        filename = f'{submission_info["submissionID"]}.{submission_info["extension"]}'

        local_directory = f'{submission_info["language"]}/{submission_info["problemID"]}'
        os.makedirs(f'{directory}/{local_directory}', exist_ok=True)

        location = f'{directory}/{local_directory}/{filename}'
        with open(location, 'w+') as file:
            file.write(code.text_content())

        info_location = f'{directory}/{local_directory}/__info.txt'
        with open(info_location, 'w+') as file:
            file.write('# This text file was auto-generated by UpCode\n\n')
            file.write(f'Problem link: {submission_info["problemURL"]}')

        print(f'[CodeForces] Updated {location} successfully')
        yield f'{local_directory}/{filename}', f'{local_directory}/__info.txt'

        time.sleep(CODEFORCES_SLEEP_TIME)

    failed_submissions = []
    for current_submission_info in get_submissions_info(username):
        try:
            yield from save_submission(current_submission_info)

        except Exception as e:
            print(f'[CodeForces] ERROR: {e}  -->  {current_submission_info["submissionID"]}')
            print('[CodeForces] Pausing temporarily to prevent rate limiting')
            failed_submissions.append(current_submission_info)
            time.sleep(CODEFORCES_SLEEP_TIME * 20)

    if failed_submissions:
        print('[CodeForces] Attempting to save failed submissions')
        for current_submission_info in failed_submissions:
            try:
                yield from save_submission(current_submission_info)

            except Exception as e:
                print(f'[CodeForces] ERROR: {e}  -->  {current_submission_info["submissionID"]}')
                print('[CodeForces] Skipping')

    else:
        print('[CodeForces] No failed submissions\n')

    print('[CodeForces] Finished')


if __name__ == '__main__':
    save_submissions('crap_the_coder', 'CodeForces')
